### ISSUE TITLE
Is line 15 correct?

### ISSUE THREAD

**Issue by jeffayle** [KeeyanGhoreshi/PokemonFireredSingleSequence#1]
I'm working on a romhack version of this based on the full inputs.txt. It would not enter a sensible name and after a lot of debugging I've figured out that changing line 15 to last 60 frames instead of 5 fixes it. This input was hitting at a time when it would not do anything, and caused the input queue to be slightly ahead when it got to the name input.

I have not tested the lua scripts in bizhawk, but this seems to be the same in 1.lua. Is that input meant to last just 5 frames?

**Comment by KeeyanGhoreshi** [comment]
I tested it just now and it seems to work as intended on my end.  My best guess is either a versioning difference, an emulator difference, or you're dropping/picking up frames somewhere.  Either that, or there's something in the lua code that is different from the way you are inputting commands from the `.txt` file.

**Comment by jeffayle** [comment]
What version of the rom are you using? Mine has the sha1sum `dd5945db9b930750cb39d00c84da8571feebf417`.

**Comment by KeeyanGhoreshi** [comment]
I'm using `41cb23d8dccc8ebd7c649cd8fbb58eeace6e2fdc`.

**Comment by jeffayle** [comment]
Okay, I was able to test both versions of the rom in bizhawk and that's not the issue. I'm still not entirely sure what's going on, but it's not a problem with your inputs.

I've got it working well enough though, I haven't run into any issues once the game actually starts. Here's the code: https://github.com/jeffayle/Pokemon-Player-Piano-Version

I credited you by your name on youtube (MartSnack), is that okay or would you prefer something else?

Awesome work on this project, this is really cool!
