### ISSUE TITLE
Problems Loading Scripts in BizHawk

### ISSUE THREAD

**Issue by tossowski** [KeeyanGhoreshi/PokemonFireredSingleSequence#2]
Hi, let me just start by saying this work is amazingly creative and must have taken a crazy amount of effort. I really respect this work!

I'm kind of new to the TAS scene and was having issues loading the lua scripts you provided. Specifically getting this error:
`NLua.Exceptions.LuaScriptException: [string "main"]:2: attempt to call global 'dbtn' (a nil value)`

which is from line 2 in movement.lua

Is this because there is a missing file which defines dbtn? I would greatly appreciate any help and am eager to try out the sequence for myself :)

**Comment by KeeyanGhoreshi** [comment]
Ah, you're right I forgot to remove references to that file when pushing.  I've pushed up a commit that should fix it, but if I missed something let me know.

**Comment by tossowski** [comment]
Works perfectly. Thanks so much!
