### ISSUE TITLE
Running script on BizHawk

### ISSUE THREAD

**Issue by Frumpy9** [KeeyanGhoreshi/PokemonFireredSingleSequence#3]
Hi there,

I recently discovered a video on YouTube that piqued my interest and I decided to try out BizHawk. I've successfully run the lua script, but I'm having an issue where all of the inputs seem to be running on top of each other when I drag in 1-9.lua and movement.lua and start the ROM. Is there a way to drop all of the files into the emulator and have them run through in sequence, or do I need to add them one by one as the previous script finishes?

Any help would be greatly appreciated. Thank you.

**Comment by KeeyanGhoreshi** [comment]
the files are meant to be run in sequence, you can start and stop them by double clicking on them in the lua console.  If you want all the files to run in sequence without intervention from you, you'll have to either write a secondary script to run them in sequence or combine 1-9.lua into one file by copying the list of inputs from each into one big list.

**Comment by Frumpy9** [comment]
Added this to my PR, #7.
