### ISSUE TITLE
Bizhawk load issue

### ISSUE THREAD

**Issue by TheHumuhumunukunukuapua** [KeeyanGhoreshi/PokemonFireredSingleSequence#8]
Hi, so several month ago I saw a TikTok on this and didn't think much of it till I go the idea to play Pokémon on my computer that's when I stumbled upon the youtube video that peaked my interest. Let me say I have no experience in coding or of bizhawk. I downloaded the script and put it in the lua console of BizHawk but keep getting an error for NLua.Exceptions.LuaScriptException: [string "main"]:4: attempt to call global 'movement' (a nil value). I have tried everything and I'm sure its my lack of knowledge. Please help me, this project is so awesome and I want to see it in action. I am very sorry if this question has already be answered or its a simple fix. any help is appreciated.  Attached is the script I have if that help, I converted to a TXT doc to attach.

[lua script.txt](https://github.com/KeeyanGhoreshi/PokemonFireredSingleSequence/files/10451989/lua.script.txt)

Thank you, Joe

**Comment by TheHumuhumunukunukuapua** [comment]
edit- I have searched the internet in hopes of finding a tutorial or some guidance into lua code with no luck.

**Comment by KeeyanGhoreshi** [comment]
It seems like you're just missing the `movement.lua` file.  Make sure you clone the entire repository and run any scripts out of the same folder as the `movement.lua` file.

**Comment by TheHumuhumunukunukuapua** [comment]
This is my last dumb question, so I got the script to run in game but when should the scrip be started? I have tried several different times and cant seem to get it to line up like the video. Seems like I just run in to walls and press the start button several times then cancel. Thank you for your help, Sorry to be a pain and a newbie that cant seem to figure it out. 

Thank you, Joe

**Comment by TheHumuhumunukunukuapua** [comment]
Again I'm sorry if I'm being a inconvenience, was going to just message frumpy9 but unsure how still exploring and figuring out this gethub thing. This is a whole new world for me.

**Comment by KeeyanGhoreshi** [comment]
You are not being an inconvenience, no worries.  The scripts are ordered 1-9 and you should start script 1 from when the game first turns on.  So in the emulator you would load the ROM, pause its execution if you need to, then start the script and unpause.  It should work after that.  This is what it looks like for me prior to starting the script:

![image](https://user-images.githubusercontent.com/24882348/213840875-fc6df6b9-66af-49e0-a30b-777211aabcd8.png)

In Bizhawk the "pause" button is under "emulation" in the menu on top.  Though the timing is not very strict, you do not have to get it exactly right or start it exactly on the screen shown above.  

After `1.lua` finishes, you can then run `2.lua` and so on, they each pick up where the last one left off.

**Comment by TheHumuhumunukunukuapua** [comment]
Thank you so much, for all the help. It is now running. looking forward to learning more about this and watching it play through. You work is amazing.

**Comment by TheHumuhumunukunukuapua** [comment]
my main issue is solved and just being curious. In the video it takes you 270 hours or something to beat the game. Wondering if theres a way to speed it up. Is it a game file issue or just how fast the system runs the script.
